package main

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

type ReportPayload struct {
	Type     string             `json:"type"`
	Summary  Summary            `json:"summary"`
	KPIs     map[string]float64 `json:"kpis"`
	ML       MLReport           `json:"ml"`
	Insights []string           `json:"insights"`
}

func writePDF(w io.Writer, p ReportPayload) error {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	pdf.SetFont("Helvetica", "B", 20)
	pdf.CellFormat(0, 12, "Business Insights Report", "", 1, "C", false, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	pdf.CellFormat(0, 6, "Generated: "+time.Now().Format("2006-01-02 15:04:05"), "", 1, "C", false, 0, "")
	pdf.Ln(4)
	pdf.SetDrawColor(220, 220, 220)
	pdf.Line(10, pdf.GetY(), 200, pdf.GetY())
	pdf.Ln(6)

	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(0, 8, "Dataset Summary", "", 1, "", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)
	pdf.CellFormat(0, 6, fmt.Sprintf("Type: %s", orNA(p.Type)), "", 1, "", false, 0, "")
	pdf.CellFormat(0, 6, fmt.Sprintf("Columns: %s", strings.Join(p.Summary.Columns, ", ")), "", 1, "", false, 0, "")
	pdf.CellFormat(0, 6, fmt.Sprintf("Shape: %d x %d", p.Summary.Shape[0], p.Summary.Shape[1]), "", 1, "", false, 0, "")

	if len(p.Summary.Missing) > 0 {
		pdf.Ln(2)
		pdf.SetFont("Helvetica", "B", 11)
		pdf.CellFormat(0, 6, "Missing Values:", "", 1, "", false, 0, "")
		pdf.SetFont("Helvetica", "", 11)
		for _, col := range sortedKeys(p.Summary.Missing) {
			pdf.CellFormat(0, 6, fmt.Sprintf("  - %s: %d", col, p.Summary.Missing[col]), "", 1, "", false, 0, "")
		}
	}
	pdf.Ln(4)
	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(0, 8, "ML KPI Predictions", "", 1, "", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)
	if len(p.ML.Predictions) == 0 {
		pdf.MultiCell(0, 6, orNA(p.ML.Message), "", "", false)
	} else {
		keys := make([]string, 0, len(p.ML.Predictions))
		for key := range p.ML.Predictions {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			prediction := p.ML.Predictions[key]
			label := strings.ReplaceAll(key, "_", " ")
			pdf.CellFormat(0, 6, fmt.Sprintf("%s: %.4f (%s)", label, prediction.Value, prediction.Model), "", 1, "", false, 0, "")
		}
	}
	pdf.Ln(4)

	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(0, 8, "Key Performance Indicators", "", 1, "", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)
	if len(p.KPIs) == 0 {
		pdf.CellFormat(0, 6, "No KPIs available", "", 1, "", false, 0, "")
	} else {
		keys := make([]string, 0, len(p.KPIs))
		for k := range p.KPIs {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			label := strings.ReplaceAll(k, "_", " ")
			pdf.CellFormat(0, 6, fmt.Sprintf("%s: %.4f", label, p.KPIs[k]), "", 1, "", false, 0, "")
		}
	}
	pdf.Ln(4)

	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(0, 8, "Top Insights", "", 1, "", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)
	if len(p.Insights) == 0 {
		pdf.CellFormat(0, 6, "No insights available", "", 1, "", false, 0, "")
	} else {
		for _, ins := range p.Insights {
			pdf.MultiCell(0, 6, "- "+ins, "", "", false)
		}
	}

	pdf.Ln(6)
	pdf.SetFont("Helvetica", "I", 9)
	pdf.CellFormat(0, 6, "Generated by IBRAE -- Business Insights Engine", "", 1, "C", false, 0, "")

	return pdf.Output(w)
}

func orNA(s string) string {
	if strings.TrimSpace(s) == "" {
		return "N/A"
	}
	return s
}
