// DEPRECATED: replaced by ../go-backend. Kept for reference only — the
// frontend no longer talks to this server.
import express from 'express';
import multer from 'multer';
import cors from 'cors';
import { PythonShell } from 'python-shell';
import path from 'path';
import PDFDocument from 'pdfkit';
import fs from 'fs';

const app = express();
app.use(cors());
app.use(express.json());

const upload = multer({ dest: 'uploads/' });

app.post('/api/upload', upload.single('file'), (req, res) => {
  // Debug log: file upload
  console.log('[UPLOAD] Received file:', req.file?.originalname, 'Stored at:', req.file?.path);
  const filePath = req.file.path;
  PythonShell.run('analyze.py', { args: [filePath] }, (err, results) => {
    if (err) {
      console.error('[UPLOAD] Python error:', err.message);
      return res.status(500).json({ error: err.message });
    }
    console.log('[UPLOAD] Python results:', results);
    res.json({ results });
  });
});


app.post('/api/report', (req, res) => {
  // Debug log: report generation
  console.log('[REPORT] Request body:', req.body);
  const { data, options } = req.body;
  PythonShell.run('generate_report.py', { args: [JSON.stringify(data), JSON.stringify(options)] }, (err, results) => {
    if (err) {
      console.error('[REPORT] Python error:', err.message);
      return res.status(500).json({ error: err.message });
    }
    console.log('[REPORT] Python results:', results);
    res.json({ report: results, pdfPath: 'report.pdf' });
  });
});

// Serve the generated PDF file
app.get('/api/download', (req, res) => {
  const filePath = path.join(process.cwd(), 'report.pdf');
  res.download(filePath, 'Business_Insights_Report.pdf', err => {
    if (err) res.status(404).send('File not found');
  });
});

// Generate PDF from posted JSON payload and stream back
app.post('/api/generate-pdf', (req, res) => {
  try {
    const payload = req.body || {};
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=report.pdf');
    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('Business Insights Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeOpacity(0.1).stroke();
    doc.moveDown();

    // Dataset summary
    doc.fontSize(14).font('Helvetica-Bold').text('Dataset Summary');
    doc.moveDown(0.2);
    const summary = payload.summary || {};
    doc.fontSize(11).font('Helvetica');
    if (Array.isArray(summary.columns)) {
      doc.text(`Columns: ${summary.columns.join(', ')}`);
    } else {
      doc.text('Columns: N/A');
    }
    if (Array.isArray(summary.shape)) {
      doc.text(`Shape: ${summary.shape.join(' x ')}`);
    }
    if (summary.missing && Object.keys(summary.missing).length > 0) {
      doc.moveDown(0.2);
      doc.text('Missing Values:');
      Object.entries(summary.missing).forEach(([col, val]) => {
        doc.text(`  • ${col}: ${val}`);
      });
    }
    doc.moveDown();

    // KPIs
    const kpis = payload.kpis || {};
    doc.fontSize(14).font('Helvetica-Bold').text('Key Performance Indicators');
    doc.moveDown(0.2);
    doc.fontSize(11).font('Helvetica');
    if (Object.keys(kpis).length === 0) {
      doc.text('No KPIs available');
    } else {
      Object.entries(kpis).forEach(([k, v]) => {
        // label and value on same line
        doc.font('Helvetica-Bold').text(k.replace(/_/g, ' '), { continued: true });
        doc.font('Helvetica').text(`: ${v}`);
      });
    }
    doc.moveDown();

    // Insights
    const insights = Array.isArray(payload.insights) ? payload.insights : [];
    doc.fontSize(14).font('Helvetica-Bold').text('Top Insights');
    doc.moveDown(0.2);
    doc.fontSize(11).font('Helvetica');
    if (insights.length === 0) {
      doc.text('No insights available');
    } else {
      insights.forEach((ins) => {
        doc.text(`• ${ins}`);
        doc.moveDown(0.1);
      });
    }

    // Footer
    doc.moveDown(1);
    doc.fontSize(9).font('Helvetica-Oblique').text('Generated by IBRAE — Business Insights Engine', { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('[PDF] generation error', err);
    res.status(500).json({ error: 'PDF creation failed' });
  }
});

app.listen(5000, () => {
  console.log('Backend running on port 5000');
});
